### PR TITLE
Create declutter.md

### PR DESCRIPTION
**Pull request by mihagazvoda**
The last sentence could also be: "Recycle the rest."

### CODE REVIEW

**Comment by koaning** [comment]
I recalled something very similar being (merged earlier)[https://github.com/koaning/thismonth.rocks/pull/8/files] and after checking it seemed it went missing. I recovered the original and don't know what to do with this one considering we also have a card for [spring cleaning](https://thismonth.rocks/idea/clean.html#p-clean).

**Comment by koaning** [comment]
I like the idea behind declutter though. It feels like there's an angle there. 

Hows about something like "remove every app from your phone" or ... "automate your email".

**Comment by koaning** [comment]
I bet there's gotta be a lot of awesome things folks can do with https://ifttt.com/

**Comment by mihagazvoda** [comment]
I agree that with `spring cleaning` and `donate` adding `decluttering` would make things too cluttered. Unless we combine both into `decluttering` but not sure if it makes sense.
What about something related to this? https://humanetech.com/resources/take-control/
IFTTT looks cool too!

**Comment by koaning** [comment]
I like that humanetech link, but it feels like that one should fall under this one: 

https://thismonth.rocks/idea/quit.html#p-quit

**Comment by koaning** [comment]
How about this. We change .. "quit social media" into "social media hygiene" 

I really like some of the ideas on the website that you've shared and they def deserve a place.

**Comment by mihagazvoda** [comment]
Nice, I like the idea! (Just installed both add-ons, thanks.:D)
And for the further reading, we can suggest https://www.goodreads.com/book/show/40672036-digital-minimalism

**Comment by koaning** [comment]
Cool. Feel free to make a PR that overrides "quit social media"

**Comment by mihagazvoda** [comment]
Working on it!

**Pull request closed without merging**
