### PR TITLE
Roller skating idea

### PR DESCRIPTION
**Pull request by kayhoogland**
When submitting an idea, consider these few points; 

- [x] We prefer ideas that won't be a burden on a budget. Money is tight for a lot of folks. 
- [x] We prefer ideas that are easy to pick up for most people. It helps if a tip is relevant for a crowd of people. Not a niche. 
- [x] We prefer ideas that are specific. Cooking is great, but it's a large topic. Instead, "perfecting a pizza" would be better. 
- [x] We prefer ideas that make it easier for people to practice social distancing. Content that helps with kids is *much* appreciated.

### CODE REVIEW

**Comment by koaning** [comment]
Let's explore the idea here a bit further. 

Rollerskating can be a perfectly fine hobby. But then again, so is cycling. I thinking having just "cycling" here does not do enough in terms of inspiration so maybe we can add something more to the idea of skating. There's plenty of types of skating too ... I mean ... [roller derby anyone](https://www.youtube.com/watch?v=0UinVsiezJY)? 

@kayhoogland got some thoughts maybe on how to expand skating? 

Also; maybe add a tag for "new hobby".

**Comment by kayhoogland** [comment]
I see what you mean. I picked up skating again after I realised I still had my skates laying around somewhere. I loved it as a kid and I think there are plenty of people who have the same experience. Seeing it on thismonth.rocks might trigger them to try it again. 

Practicing social distancing might be hard in a roller derby though 😛 . Some ideas that come to mind:

- Swap your bike for your skates every now and then
- Learn to skate backwards
- Take the ramp in the closest skatepark
- Teach your kids to skate

**Comment by koaning** [comment]
I like this one "Swap your bike for your skates every now and then" 

But i might change it to "Change your mode of transport" ... this way folks can try out biking, public transport, carpooling and skating ... what do you think?

**Comment by kayhoogland** [comment]
I like it! PR is updated, title was a bit long so I went for 'Swap transport`

**Comment by koaning** [comment]
https://thismonth.rocks/idea/skate.html#p-skate

**Pull request merged**
