### PR TITLE
New idea: join a union

### PR DESCRIPTION
**Pull request by Nelson-AM**
When submitting an idea, consider these few points; 

- [ ] We prefer ideas that won't be a burden on a budget. Money is tight for a lot of folks. 
- [ ] We prefer ideas that are easy to pick up for most people. It helps if a tip is relevant for a crowd of people. Not a niche. 
- [ ] We prefer ideas that are specific. Cooking is great, but it's a large topic. Instead, "perfecting a pizza" would be better. 
- [ ] We prefer ideas that make it easier for people to practice social distancing. Content that helps with kids is *much* appreciated.

### CODE REVIEW

**Comment by koaning** [comment]
I see where you're going with this. But there's a few comments. 

1. I want to prevent that the website is a reminder of covid. After all, there will be a time when all of this is over. And as of such I'd prefer not to have a reference to "trying times" and instead have something that has a 'timeless' reference. 
2. The link you posted doesn't lead anywhere.
3. Might it be valid to do a small pivot? A union is a bit of a loaded term in the US, but the direction of "understand your rights" is definately something that folks will get. This way, a union can be an example, but the general goal is less of a politically loaded term.

**Comment by Nelson-AM** [comment]
Fixed points 1 and 2 from your comment. As for 3, I understand where you're coming from and that it might be a loaded term, however, I'm not sure how to rephrase this without dancing around the subject too much. I'm open to suggestions!

**Comment by koaning** [comment]
I just realised that you've got another interesting thing there. A tag for `work`. 

There's some interesting tickets that deserve exploring with just that theme; 

- invest in ergonomics
- prepare your lunch for work
- pomodoro (needs to add the tag) 

I just checked the site, are you sure it is a reliable source? 

image

**Comment by Nelson-AM** [comment]
Those are some good ideas! I'd say ITUC is a reputable source being a large confederation; not sure what issue Cloudflare ran into there though. Haven't had issues with their site myself.

**Comment by koaning** [comment]
It seems the link is [back](https://www.ituc-csi.org/). Still the website is very large ... where is the button to find a union?

**Comment by koaning** [comment]
Actually ... the more I think about it ... I think I should put my foot down here. It's something that I do not want to support here. There's a lot of stories of folks who get fired from starting a union (there's even an episode in The Office (US) about it) and I want to be careful with 'inspiring' people to take such personal risks.

**Comment by Nelson-AM** [comment]
> It seems the link is [back](https://www.ituc-csi.org/). Still the website is very large ... where is the button to find a union?

The link could be updated to point to their [address book](https://www.ituc-csi.org/about-us?page=abook) where one can search for affiliated organisations per region or country. Alternatively, there's the [IWW](https://iww.org/), an international union for all workers.

> Actually ... the more I think about it ... I think I should put my foot down here. It's something that I do not want to support now. There's a lot of stories of folks who get fired from starting a union (there's even an episode in The Office (US) about it) and I want to be careful with 'inspiring' people to take such personal risks in a time where the risk of getting fired (even for doing the right thing) is high.

I understand the need to tread carefully here since, as you mention, the personal risk can be very high in this situation. Especially because that personal risk exists and it's a solidarity action towards a greater good, it would sadden me to completely do away with this idea. Would it suffice to add a disclaimer to check in with your employer's policy or local labour laws before considering unionizing? Alternatively, we could go for something along the lines of 'familiarize yourself with your rights as a worker or local labour laws'. (The latter can be with or without mentioning the U-word. 😛)

**Comment by koaning** [comment]
Would it then be a middle road to mention the option of exploring a union but that the subject is "understand your rights"?

**Comment by koaning** [comment]
The nice thing about this angle is that there's also consumers right (consumentenbond) that we might highlight.

**Pull request closed without merging**
