### PR TITLE
 Create ethical-alternative.md

### PR DESCRIPTION
**Pull request by mihagazvoda**
When submitting an idea, consider these few points; 

- [ ] We prefer ideas that won't be a burden on a budget. Money is tight for a lot of folks. 
- [ ] We prefer ideas that are easy to pick up for most people. It helps if a tip is relevant for a crowd of people. Not a niche. 
- [ ] We prefer ideas that are specific. Cooking is great, but it's a large topic. Instead, "perfecting a pizza" would be better. 
- [ ] We prefer ideas that make it easier for people to practice social distancing. Content that helps with kids is *much* appreciated.

### CODE REVIEW

**Comment by mihagazvoda** [comment]
feel free to add/improve the content!

**Comment by koaning** [comment]
Ah I forgot about that website, nice addition! 

I wonder how the word "ethical" might trigger people ... would you be against ... "tech cleanup"?
I am also wondering the word explore is better ... "explore ethical tech"?

**Comment by mihagazvoda** [comment]
Thanks!
I agree with your concern about the word "ethical". If you plan to use somewhere it might be good to use quotation marks? Just brainstorming...
Tech cleanup sounds a bit like removing tech from your life, doesn't it? Maybe just "tech alternatives"? Not sure. You can go with "tech cleanup" and we can change it later on. 
I also prefer the word "explore"!

**Comment by koaning** [comment]
I agree with tech cleanup. Should be up in 5 mins.

**Comment by mihagazvoda** [comment]
Great! I like your changes!

**Pull request merged**
