### PR TITLE
Create a meetup.md

### PR DESCRIPTION
**Pull request by versionbaygt**
Why not organize an online meetup?

When submitting an idea, consider these few points; 

- [ ] We prefer ideas that won't be a burden on a budget. Money is tight for a lot of folks. 
- [ ] We prefer ideas that are easy to pick up for most people. It helps if a tip is relevant for a crowd of people. Not a niche. 
- [ ] We prefer ideas that are specific. Cooking is great, but it's a large topic. Instead, "perfecting a pizza" would be better. 
- [ ] We prefer ideas that make it easier for people to practice social distancing. Content that helps with kids is *much* appreciated.

### CODE REVIEW

**Comment by koaning** [comment]
There's something there, my concern is that meetups might be very tech-specific though. They are perhaps less known to people not in the tech filter bubble. The website is not perfectly consistent with this but it intended for a general crowd. 

Thinking out loud though if we pivot a bit towards "hangout digitally" ... does that make sense?  We can then also add links that explain to people how to get started.

**Comment by versionbaygt** [comment]
@koaning indeed maybe you are right, instead of meetup which could be a bit overwhelming, digital hangout might be a better term. And in the instructions we could add: how to setup a video call with: google hangout, zoom and teams?

**Comment by koaning** [comment]
Something along those lines feels more fitting, aye :) .

**Comment by koaning** [comment]
Another angle might be; who would you call? A long-lost friend? A family member who appreciates it? There might be something there to make it more tangible too ... more tangible usually means more people will do it.

**Comment by koaning** [comment]
Radio silence. 

If we're dropping the idea, mind if I close the PR?

**Pull request closed without merging**
